[workspace]
members = ["crates/img-core", "crates/img-cli", "desktop"]
default-members = ["crates/img-core", "crates/img-cli"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
repository = "https://github.com/liyown/img"

[profile.dev]
debug = 0

[profile.release]
strip = "debuginfo"
